/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BeFoundFrameworkRouteImport } from './routes/be-found-framework'
import { Route as AiReportRouteImport } from './routes/ai-report'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BeFoundFrameworkRoute = BeFoundFrameworkRouteImport.update({
  id: '/be-found-framework',
  path: '/be-found-framework',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReportRoute = AiReportRouteImport.update({
  id: '/ai-report',
  path: '/ai-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-report': typeof AiReportRoute
  '/be-found-framework': typeof BeFoundFrameworkRoute
  '/contact': typeof ContactRoute
  '/results': typeof ResultsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-report': typeof AiReportRoute
  '/be-found-framework': typeof BeFoundFrameworkRoute
  '/contact': typeof ContactRoute
  '/results': typeof ResultsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-report': typeof AiReportRoute
  '/be-found-framework': typeof BeFoundFrameworkRoute
  '/contact': typeof ContactRoute
  '/results': typeof ResultsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-report'
    | '/be-found-framework'
    | '/contact'
    | '/results'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-report'
    | '/be-found-framework'
    | '/contact'
    | '/results'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-report'
    | '/be-found-framework'
    | '/contact'
    | '/results'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiReportRoute: typeof AiReportRoute
  BeFoundFrameworkRoute: typeof BeFoundFrameworkRoute
  ContactRoute: typeof ContactRoute
  ResultsRoute: typeof ResultsRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/be-found-framework': {
      id: '/be-found-framework'
      path: '/be-found-framework'
      fullPath: '/be-found-framework'
      preLoaderRoute: typeof BeFoundFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-report': {
      id: '/ai-report'
      path: '/ai-report'
      fullPath: '/ai-report'
      preLoaderRoute: typeof AiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiReportRoute: AiReportRoute,
  BeFoundFrameworkRoute: BeFoundFrameworkRoute,
  ContactRoute: ContactRoute,
  ResultsRoute: ResultsRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
